apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tilopos-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
    - hosts:
        - app.tilopos.id
        - api.tilopos.id
      secretName: tilopos-tls
  rules:
    - host: app.tilopos.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tilopos-web
                port:
                  number: 80
    - host: api.tilopos.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tilopos-backend
                port:
                  number: 80
